# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:01
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170413_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='위도/경도 포맷으로 입력하세요.', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
