# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0008_auto_20170503_0146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameuser',
            unique_together=set([]),
        ),
    ]
