# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0009_auto_20170503_0152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameuser',
            unique_together=set([('server_name', 'username')]),
        ),
    ]
